version: "3.9"

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - /workspace/Data:/data

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=mydatabase

  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=mydatabase
    volumes:
      - ./creating_Tables/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - db_data:/var/lib/mysql
    command: --init-file /docker-entrypoint-initdb.d/create_tables.sql


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    ports:
      - "8081:80"

volumes:
  db_data:

#reference
#https://hub.docker.com/r/phpmyadmin/phpmyadmin
