version: "3.9"

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - /workspace/Data:/data

  mongo:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_DATABASE=mydatabase
      - MONGO_DB=mydatabase
    volumes:
      - mongo_data:/data/db

  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=mydatabase
    volumes:
      - ./creating_Tables/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - db_data:/var/lib/mysql
    command: --init-file=/docker-entrypoint-initdb.d/create_tables.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    ports:
      - "8081:80"

  mongo-express:
    image: mongo-express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
    ports:
      - "8082:8081"
    depends_on:
      - mongo

volumes:
  db_data:
  mongo_data:

#reference
#https://hub.docker.com/r/phpmyadmin/phpmyadmin
