CREATE TABLE LOCATION (
  LOC_ID INT AUTO_INCREMENT PRIMARY KEY,
  LOC_NAME VARCHAR(50),
  ADDRESS VARCHAR(255)
);

CREATE TABLE DEPARTMENT (
  DEPT_ID INT AUTO_INCREMENT PRIMARY KEY,
  DEPT_NAME VARCHAR(50),
  LOC_ID INT,
  FOREIGN KEY (LOC_ID) REFERENCES LOCATION(LOC_ID)
);

CREATE TABLE EMPLOYEE (
  EMPNO INT AUTO_INCREMENT PRIMARY KEY,
  ENAME VARCHAR(50),
  JOB VARCHAR(50),
  MGR INT,
  HIREDATE DATETIME,
  SAL DECIMAL(7, 2),
  COMM DECIMAL(7, 2),
  DEPTNO INT,
  FOREIGN KEY (DEPTNO) REFERENCES DEPARTMENT(DEPT_ID)
);

CREATE TABLE BENEFIT (
  BENEFIT_ID INT AUTO_INCREMENT PRIMARY KEY,
  BENEFIT_NAME VARCHAR(50),
  DESCRIPTION VARCHAR(255)

);

CREATE TABLE EMPLOYEE_BENEFIT (
  EMP_ID INT,
  BENEFIT_ID INT,
  FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMPNO),
  FOREIGN KEY (BENEFIT_ID) REFERENCES BENEFIT(BENEFIT_ID)
);
