CREATE TABLE LOCATION (
  LOC_ID INT AUTO_INCREMENT PRIMARY KEY,
  LOC_NAME VARCHAR(50),
  ADDRESS VARCHAR(255),
  COUNTRY VARCHAR(50)
);

CREATE TABLE DEPARTMENT (
  DEPT_ID INT AUTO_INCREMENT PRIMARY KEY,
  DEPT_NAME VARCHAR(50),
  LOC_ID INT,
  FOREIGN KEY (LOC_ID) REFERENCES LOCATION(LOC_ID)
);

CREATE TABLE EMPLOYEE (
  EMPNO INT AUTO_INCREMENT PRIMARY KEY,
  ENAME VARCHAR(50),
  JOB VARCHAR(50),
  MGR INT,
  HIREDATE DATETIME,
  SAL DECIMAL(7, 2),
  COMM DECIMAL(7, 2),
  DEPTNO INT,
  FOREIGN KEY (DEPTNO) REFERENCES DEPARTMENT(DEPT_ID)
);

CREATE TABLE BENEFIT (
  BENEFIT_ID INT AUTO_INCREMENT PRIMARY KEY,
  BENEFIT_NAME VARCHAR(50),
  DESCRIPTION VARCHAR(255)

);

CREATE TABLE EMPLOYEE_BENEFIT (
  EMP_ID INT,
  BENEFIT_ID INT,
  FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMPNO),
  FOREIGN KEY (BENEFIT_ID) REFERENCES BENEFIT(BENEFIT_ID)
);


-- Insert data into the LOCATION table
INSERT INTO LOCATION (LOC_NAME, ADDRESS)
VALUES
  ('New York Office', '123 Main St, New York, USA'),
  ('London Office', '456 Park Lane, London, UK');

-- Insert data into the DEPARTMENT table
INSERT INTO DEPARTMENT (DEPT_NAME, LOC_ID)
VALUES
  ('Sales', 1),
  ('Marketing', 1),
  ('Engineering', 2);

-- Insert data into the EMPLOYEE table
INSERT INTO EMPLOYEE (ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES
  ('John Smith', 'Manager', NULL, '2022-01-01', 5000.00, NULL, 1),
  ('Jane Doe', 'Sales Representative', 1, '2022-02-01', 3000.00, 500.00, 1),
  ('Mark Johnson', 'Marketing Specialist', 1, '2022-03-01', 3500.00, NULL, 2),
  ('Sarah Williams', 'Software Engineer', 3, '2022-04-01', 4000.00, NULL, 3);

-- Insert data into the BENEFIT table
INSERT INTO BENEFIT (BENEFIT_NAME, DESCRIPTION)
VALUES
  ('Health Insurance', 'Comprehensive health insurance coverage'),
  ('Paid Time Off', 'Paid vacation and sick leave'),
  ('Retirement Plan', '401(k) matching contributions');

-- Insert data into the EMPLOYEE_BENEFIT table
INSERT INTO EMPLOYEE_BENEFIT (EMP_ID, BENEFIT_ID)
VALUES
  (2, 1),
  (3, 1),
  (4, 1),
  (4, 2),
  (4, 3);
